spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: c2dmemJpZGxqO29GS1BBbHtPSVVHWUZUSEpZR1VITElPSktQYXNkZg==
    access: 3600000
    refresh: 2592000000